export const actionType = {
    REQUEST_LOGIN: 'REQUEST_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    FETCH_NEWS: 'FETCH_NEWS',
    ADD_NEWS: 'ADD_NEWS',
    DELETE_NEWS: 'DELETE_NEWS'
  }